### PR TITLE
AB#33 Create ssl.pem

### PR DESCRIPTION
**Pull request by El-SaMa**
ssl cert

### CODE REVIEW

**Review by HeidiN86 — APPROVED** [review]
Looking good!

**Review by tiibuturner — APPROVED** [review]
Amazing job!

**Review by Varski — CHANGES_REQUESTED** [review]
This is not right :(

**Review by tiibuturner — APPROVED** [review]
Niccccccce!

**Comment by El-SaMa** [comment]
hmm

**Review by Varski — APPROVED** [review]
Okay now this is fine

**Review by HeidiN86 — APPROVED** [review]
Looks good, I told you already!

**Pull request merged**
